### ISSUE TITLE
FEVER dataset version

### ISSUE THREAD

**Issue by ZJZhang123** [CuteyThyme/RISK#1]
Hi, I would like to ask which version of the FEVER dataset you are using.

**Comment by CuteyThyme** [comment]
We use the [FEVER](https://fever.ai/dataset/fever.html) dataset, following the benchmark as other baselines take.

**Comment by ZJZ1223** [comment]
Got it, thanks a lot!

**Comment by ZJZhang123** [comment]
> We use the [FEVER](https://fever.ai/dataset/fever.html) dataset, following the benchmark as other baselines take.

Got it, thanks a lot!

**Comment by ZJZhang123** [comment]
Hi, I have another related question to ask, how did you retrieve  the evidence corresponding to the claim in order to make FEVER dataset? @CuteyThyme

**Comment by CuteyThyme** [comment]
I upload the processed FEVER dataset into this [link](https://drive.google.com/drive/folders/1SaqejxU8ubwK5EqWQexR-FS4yEp8EvuB?usp=share_link). Wish it can help you.

**Comment by ZJZhang123** [comment]
> 

Got it ! Thank you so much, this helps me a lot.
