### ISSUE TITLE
Mismatch of experimental reproduction results

### ISSUE THREAD

**Issue by ZJZhang123** [CuteyThyme/RISK#2]
Hi, I reproduced the experiments according to the steps in your readme, but the results don't quite match, any suggestions?

This is a comparison between my experimental results and the results in the paper. As you can see, the results seem to be misaligned.

*My results of exps*:

![my_exp](https://user-images.githubusercontent.com/71306074/209432161-9edf43af-98d4-43ae-aae2-80399cd8869a.jpg)

*Paper results of exps*:

![original_exp](https://user-images.githubusercontent.com/71306074/209432164-5e3fa7bd-5bdf-4d88-99e3-18e48eab11c3.jpg)

**Comment by CuteyThyme** [comment]
I think you should better check the dataset and the saved model. I am sure the empirical results are aligned with the task during my experiments.
